# Generated by Django 4.1.7 on 2023-02-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testovoe',
            fields=[
                ('rang', models.IntegerField()),
                ('os', models.CharField(max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Value', models.IntegerField()),
                ('Alarms', models.CharField(max_length=100)),
            ],
        ),
    ]
