# Generated by Django 4.1.7 on 2023-02-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testovoe',
            name='comment',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
