# Generated by Django 4.1.7 on 2023-02-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_testovoe_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('item_id', models.IntegerField()),
                ('comment', models.TextField(max_length=250)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='testovoe',
            name='comment',
        ),
    ]
